# Generated by Django 3.1.5 on 2022-03-03 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Let',
            fields=[
                ('sifraLeta', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('day', models.DateField()),
                ('od', models.CharField(max_length=30)),
                ('do', models.CharField(max_length=30)),
                ('cenaE', models.FloatField()),
                ('brojMesta', models.IntegerField()),
                ('cenaB', models.FloatField()),
                ('prtljagE', models.BooleanField()),
                ('vremePolaska', models.TimeField()),
                ('vremeDolaska', models.TimeField()),
            ],
        ),
    ]
