# Generated by Django 3.1.5 on 2022-03-04 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Let',
            new_name='Flight',
        ),
    ]
