# Generated by Django 3.1.5 on 2022-03-15 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0002_auto_20220304_1754'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flight',
            name='cenaB',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='flight',
            name='cenaE',
            field=models.IntegerField(),
        ),
    ]
